name = "telegram-bot-proxy"
main = "telegram-bot-proxy.js"
compatibility_date = "2025-08-01"

# Uncomment the below if deploying to a custom domain / route
# routes = [
#   "https://your-custom-domain.com/*"
# ]
